version: '3.9'

services:

  db:
    image: postgres
    env_file:
      - ./docker/env/db_variables.env
      - ./docker/env/envkey.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./htmlcov:/app/htmlcov # TODO: save it in the host automatically somehow

  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file:
      - ./docker/env/db_variables.env
      - ./docker/env/auth_variables.env
      - ./docker/env/envkey.env
      - ./docker/env/django_variables.env
      - ./docker/server/django_variables.env
    volumes:
      - static_volume:/app/static
      - media:/app/media
    ports:
      - 80:8000
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8000/ || exit 1" ]
      interval: 60s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

volumes:
  static_volume: {}
  media: {}
  postgres_data: {}
