version: "3.9"

include:
  - docker-compose-db.yaml

services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file:
      - ./docker/server/doppler.env
      - ./docker/server/local_env.env
    volumes:
      - static_volume:/app/static
      - media:/app/media
      - ./htmlcov:/app/htmlcov # TODO: save it in the host automatically somehow
    ports:
      - 80:80
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:80/ || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

volumes:
  static_volume: {}
  media: {}
