version: '3.9'

services:

  db:
    image: postgres
    env_file:
      - ./docker/env/db_variables.env
      - ./docker/env/envkey.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file:
      - ./docker/env/db_variables.env
      - ./docker/env/django_variables.env
      - ./docker/env/envkey.env
    entrypoint: ./server-entrypoint.sh
    volumes:
      - static_volume:/app/django_static
    expose:
      - 8000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8000/admin || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/django_static
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on:
      server:
        condition: service_healthy

volumes:
  static_volume: {}
  postgres_data: {}
