# Generated by Django 3.2 on 2023-09-08 17:59

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorStatus',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='PENDING_APPROVAL', max_length=100, no_check_for_status=True),
        ),
    ]
