# Generated by Django 3.2 on 2023-11-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='websites',
        ),
        migrations.AddField(
            model_name='doctorlocation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
