# Generated by Django 3.2 on 2023-09-07 11:40

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorcategory',
            old_name='tag',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctorspeciality',
            old_name='speciality',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='categoris',
            field=models.ManyToManyField(blank=True, to='doctors.DoctorCategory'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='doctors.DoctorSpeciality'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='websites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, null=True, size=None),
        ),
    ]
