# Generated by Django 3.2 on 2023-09-07 14:55

from django.db import migrations
import django_enumfield.db.fields
import doctors.models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0002_auto_20230907_1140"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="status",
            field=django_enumfield.db.fields.EnumField(
                default=0, enum=doctors.models.DoctorStatus
            ),
        ),
    ]
