# Generated by Django 3.2 on 2023-11-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231124_1954'),
        ('doctors', '0002_auto_20231119_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
