# Generated by Django 3.2 on 2023-09-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20230908_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorspeciality',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
