# Generated by Django 3.2 on 2023-09-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20230908_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorspeciality',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
