# Generated by Django 3.2 on 2023-11-25 17:01

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='approved_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'APPROVED'}),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rejected_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'REJECTED'}),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='approved_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'APPROVED'}),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='rejected_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'REJECTED'}),
        ),
    ]
