# Generated by Django 3.2 on 2023-10-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons'),
        ),
    ]
