# Generated by Django 3.2 on 2023-11-26 13:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_auto_20231125_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreview',
            name='rating',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.5'), '0.5'), (Decimal('1'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5'), '5.0')], decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
