# Generated by Django 3.2 on 2023-09-16 18:53

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_auto_20230914_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rejected_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'REJECTED'}),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
