# Generated by Django 3.2 on 2023-10-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctorcategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorcategory',
            name='icon',
        ),
    ]
