# Generated by Django 3.2 on 2023-10-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_doctorcategory_icon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorlocation',
            unique_together={('doctor', 'address')},
        ),
    ]
