# Generated by Django 3.2 on 2023-11-30 05:30

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231124_1954'),
        ('doctors', '0008_auto_20231128_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreview',
            name='deleted_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'DELETED'}),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
