# Generated by Django 3.2 on 2023-12-23 06:42

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
        ('doctors', '0012_alter_doctor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreview',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DoctorIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', model_utils.fields.StatusField(choices=[('PENDING', 'PENDING'), ('MODIFICATION_NEEDED', 'MODIFICATION_NEEDED'), ('PUBLISHED', 'PUBLISHED'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED')], default='PENDING', max_length=100, no_check_for_status=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rejected_at', model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'REJECTED'})),
                ('deleted_at', model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'DELETED'})),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('published_at', model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'PUBLISHED'})),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
