# Generated by Django 3.2 on 2023-12-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_rename_address_doctorlocation_long_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlocation',
            name='short_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
