# Generated by Django 3.2 on 2025-10-19 20:53

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_doctorlocation_short_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='PENDING APPROVAL', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='doctorlocation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
