# Generated by Django 3.2 on 2023-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_auto_20231119_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(blank=True, max_length=200)),
                ('saved_doctors', models.ManyToManyField(to='doctors.Doctor')),
            ],
        ),
    ]
