# Generated by Django 3.2 on 2023-11-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20231119_0516'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remote_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_doctors',
            field=models.ManyToManyField(blank=True, to='doctors.Doctor'),
        ),
    ]
