# This workflow will build and push a new container image to Amazon ECR,
# when there is a push to the "main" branch.

name: Deploy to Amazon ECR

on:
    push:
        branches: ["main", "aws-ecr"]

env:
    AWS_REGION: us-east-1 # set this to your preferred AWS region, e.g. us-west-1 # TODO: change?
    ECR_REPOSITORY: theyellowhub # set this to your Amazon ECR repository name
    SERVER_IMAGE_TAG: themap_server
    NGINX_IMAGE_TAG: themap_nginx
    # CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
    # containerDefinitions section of your task definition

permissions:
    contents: read

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: ECR

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to Amazon ECR
              id: build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  IMAGE_TAG: ${{ env.IMAGE_TAG }}
              run: |
                  # Build "server" docker container and push it to ECR
                  docker build . -f ./docker/backend/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$SERVER_IMAGE_TAG
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SERVER_IMAGE_TAG
                  echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$SERVER_IMAGE_TAG" >> $GITHUB_OUTPUT
                  # Build "nginx" docker container and push it to ECR
                  docker build . -f ./docker/nginx/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$NGINX_IMAGE_TAG
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$NGINX_IMAGE_TAG
                  echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$NGINX_IMAGE_TAG" >> $GITHUB_OUTPUT
