# This workflow builds and pushes a new container image to Slipplane

name: Deploy to Slipplane

on:
    push:
        branches: ["sliplane"]

env:
    IMAGE_TAG_PREFIX: ${{ vars.AWS_LIGHTSAIL_SERVICE }}

    permissions:
    contents: read

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: Sliplane
        strategy:
            matrix:
                IMAGE_TAG: [server] # [backend, frontend]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build
              env:
                  IMAGE_TAG: ${{ matrix.IMAGE_TAG }}
              run: |
                  docker build . -f ./docker/${{ env.IMAGE_TAG }}/Dockerfile -t ${{ env.IMAGE_TAG }} --build-arg DOPPLER_PROJECT=${{ vars.DOPPLER_PROJECT }} --build-arg DOPPLER_CONFIG=${{ vars.DOPPLER_CONFIG }} --build-arg DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }}

            - name: Slipplane
              run: |
                  curl -X GET ${{ secrets.SLIPLANE_DEPLOY_HOOK }}
